CREATE OR REPLACE PACKAGE PKG_LOG AS
-- Copyright (c) 2021 Pierre-Sanguinetti

iDefaultInsLvl INTEGER := 1000;
iDefaultCommitLvl INTEGER := 1;
iDefaultOutputLvl INTEGER := 0;

PROCEDURE LOG_LINE(sText IN VARCHAR2, iInsLvl IN INTEGER DEFAULT NULL, iCommitLvl IN INTEGER DEFAULT NULL, iOutputLvl IN INTEGER DEFAULT NULL, sPad IN VARCHAR2 DEFAULT '   ');

--MOD_20211016.exc_err_log
PROCEDURE LOG_INDENT_INC(bDoModififyLvl IN BOOLEAN DEFAULT TRUE, iNbLevel IN INTEGER DEFAULT 1);

--MOD_20211016.exc_err_log
PROCEDURE LOG_INDENT_DEC(bDoModififyLvl IN BOOLEAN DEFAULT TRUE, iNbLevel IN INTEGER DEFAULT 1);

--MOD_20211016.exc_err_log
PROCEDURE LOG_LVL_INC(iNbLevel IN INTEGER DEFAULT 1);

--MOD_20211016.exc_err_log
PROCEDURE LOG_LVL_DEC(iNbLevel IN INTEGER DEFAULT 1);

PROCEDURE LOG_BEGIN(sProcName IN VARCHAR2, iInsLvl IN INTEGER DEFAULT NULL, iCommitLvl IN INTEGER DEFAULT NULL, iOutputLvl IN INTEGER DEFAULT NULL, sPad IN VARCHAR2 DEFAULT '   ', bDoModififyLvl IN BOOLEAN DEFAULT TRUE);

--MOD_20200120.exc_warning
PROCEDURE LOG_END2(sProcName IN VARCHAR2, iInsLvl IN INTEGER DEFAULT NULL, iCommitLvl IN INTEGER DEFAULT NULL, iOutputLvl IN INTEGER DEFAULT NULL, sPad IN VARCHAR2 DEFAULT '   ', bDoModififyLvl IN BOOLEAN DEFAULT TRUE, iExitCode IN INTEGER DEFAULT NULL);
PROCEDURE LOG_END(sProcName IN VARCHAR2, iInsLvl IN INTEGER DEFAULT NULL, iCommitLvl IN INTEGER DEFAULT NULL, iOutputLvl IN INTEGER DEFAULT NULL, sPad IN VARCHAR2 DEFAULT '   ', bDoModififyLvl IN BOOLEAN DEFAULT TRUE, bSuccess BOOLEAN DEFAULT NULL);


-- Procedure de log sans COMMIT a utiliser dans les triggers (NC <=> No Commit)

PROCEDURE LOG_LINE_NC(sText IN VARCHAR2, iInsLvl IN INTEGER DEFAULT NULL, iOutputLvl IN INTEGER DEFAULT NULL, sPad IN VARCHAR2 DEFAULT '   ');

PROCEDURE LOG_BEGIN_NC(sProcName IN VARCHAR2, iInsLvl IN INTEGER DEFAULT NULL, iOutputLvl IN INTEGER DEFAULT NULL, sPad IN VARCHAR2 DEFAULT '   ', bDoModififyLvl IN BOOLEAN DEFAULT TRUE);

PROCEDURE LOG_END_NC(sProcName IN VARCHAR2, iInsLvl IN INTEGER DEFAULT NULL, iOutputLvl IN INTEGER DEFAULT NULL, sPad IN VARCHAR2 DEFAULT '   ', bDoModififyLvl IN BOOLEAN DEFAULT TRUE);

END PKG_LOG;
/
show err
